### PR TITLE
Add a few more profane words

### PR DESCRIPTION
**Pull request by SeriyBg**
Add a few more profane words

### CODE REVIEW

**Review by Samasaur1 — CHANGES_REQUESTED** [review]
Please rebase off of `master` or merge `master` into your branch so that I can merge this. Thanks!

**Comment by SeriyBg** [comment]
@Samasaur1 done. Sorry for taking so long

**Review by Samasaur1 — APPROVED** [review]
LGTM

**Comment by Samasaur1** [comment]
Thanks!

**Pull request merged**
